FairLearn:
  classpath: fairlearn.reductions.ExponentiatedGradient
  base_estimator:
    classpath: sklearn.ensemble.GradientBoostingClassifier
    kwargs:
      n_estimators:
        type: int
        range: [50, 500]
        log: True
      learning_rate:
        type: float
        range: [0.01, 0.3]
        log: True
      max_depth:
        type: int
        range: [3, 10]
        log: False
      min_samples_split:
        type: int
        range: [2, 20]
        log: False
      min_samples_leaf:
        type: int
        range: [1, 10]
        log: False
      subsample:
        type: float
        range: [0.6, 1.0]
        log: False
      random_state: 42
  constraint_type: "PredictiveEquality"
  kwargs:
    eps:
      type: float
      range: [0.01, 0.5]
      log: False
    nu:
      type: float
      range: [0.01, 0.5]
      log: False
    eta0:
      type: float
      range: [0.1, 10.0]
      log: True
    max_iter:
      type: int
      range: [10, 100]
      log: False