# python fit_causal_models.py --model-type lgbm --output-dir output/adult/med/lgbm
# python fit_causal_models.py --model-type linear --output-dir output/adult/med/linear
# python fit_causal_models.py --model-type causalflow --output-dir output/adult/med/causalflow
# python fit_causal_models.py --model-type diffusion --output-dir output/adult/med/diffusion

python fit_causal_models_gen_eval_counterfactuals.py --model-type diffusion --output-dir output/adult/med/diffusion --world-indexes "0"
python fit_causal_models_gen_eval_counterfactuals.py --model-type diffusion --output-dir output/adult/med/diffusion --world-indexes "1"
python fit_causal_models_gen_eval_counterfactuals.py --model-type diffusion --output-dir output/adult/med/diffusion --world-indexes "2"
python fit_causal_models_gen_eval_counterfactuals.py --model-type diffusion --output-dir output/adult/med/diffusion --world-indexes "3"
python fit_causal_models_gen_eval_counterfactuals.py --model-type diffusion --output-dir output/adult/med/diffusion --world-indexes "4"
python fit_causal_models_gen_eval_counterfactuals.py --model-type diffusion --output-dir output/adult/med/diffusion --world-indexes "5"
python fit_causal_models_gen_eval_counterfactuals.py --model-type diffusion --output-dir output/adult/med/diffusion --world-indexes "6"
python fit_causal_models_gen_eval_counterfactuals.py --model-type diffusion --output-dir output/adult/med/diffusion --world-indexes "7"
python fit_causal_models_gen_eval_counterfactuals.py --model-type diffusion --output-dir output/adult/med/diffusion --world-indexes "8"
python fit_causal_models_gen_eval_counterfactuals.py --model-type diffusion --output-dir output/adult/med/diffusion --world-indexes "9"
python fit_causal_models_gen_eval_counterfactuals.py --model-type diffusion --output-dir output/adult/med/diffusion --world-indexes "10"
python fit_causal_models_gen_eval_counterfactuals.py --model-type diffusion --output-dir output/adult/med/diffusion --world-indexes "11"
python fit_causal_models_gen_eval_counterfactuals.py --model-type diffusion --output-dir output/adult/med/diffusion --world-indexes "12"
python fit_causal_models_gen_eval_counterfactuals.py --model-type diffusion --output-dir output/adult/med/diffusion --world-indexes "13"
python fit_causal_models_gen_eval_counterfactuals.py --model-type diffusion --output-dir output/adult/med/diffusion --world-indexes "14"
python fit_causal_models_gen_eval_counterfactuals.py --model-type diffusion --output-dir output/adult/med/diffusion --world-indexes "15"
python fit_causal_models_gen_eval_counterfactuals.py --model-type diffusion --output-dir output/adult/med/diffusion --world-indexes "16"
python fit_causal_models_gen_eval_counterfactuals.py --model-type diffusion --output-dir output/adult/med/diffusion --world-indexes "17"
python fit_causal_models_gen_eval_counterfactuals.py --model-type diffusion --output-dir output/adult/med/diffusion --world-indexes "18"
python fit_causal_models_gen_eval_counterfactuals.py --model-type diffusion --output-dir output/adult/med/diffusion --world-indexes "19"
python fit_causal_models_gen_eval_counterfactuals.py --model-type diffusion --output-dir output/adult/med/diffusion --world-indexes "20"
python fit_causal_models_gen_eval_counterfactuals.py --model-type diffusion --output-dir output/adult/med/diffusion --world-indexes "21"
python fit_causal_models_gen_eval_counterfactuals.py --model-type diffusion --output-dir output/adult/med/diffusion --world-indexes "22"
python fit_causal_models_gen_eval_counterfactuals.py --model-type diffusion --output-dir output/adult/med/diffusion --world-indexes "23"
python fit_causal_models_gen_eval_counterfactuals.py --model-type diffusion --output-dir output/adult/med/diffusion --world-indexes "24"
python fit_causal_models_gen_eval_counterfactuals.py --model-type diffusion --output-dir output/adult/med/diffusion --world-indexes "25"
python fit_causal_models_gen_eval_counterfactuals.py --model-type diffusion --output-dir output/adult/med/diffusion --world-indexes "26"
python fit_causal_models_gen_eval_counterfactuals.py --model-type diffusion --output-dir output/adult/med/diffusion --world-indexes "27"
python fit_causal_models_gen_eval_counterfactuals.py --model-type diffusion --output-dir output/adult/med/diffusion --world-indexes "28"
python fit_causal_models_gen_eval_counterfactuals.py --model-type diffusion --output-dir output/adult/med/diffusion --world-indexes "29"
python fit_causal_models_gen_eval_counterfactuals.py --model-type diffusion --output-dir output/adult/med/diffusion --world-indexes "30"
python fit_causal_models_gen_eval_counterfactuals.py --model-type diffusion --output-dir output/adult/med/diffusion --world-indexes "31"
python fit_causal_models_gen_eval_counterfactuals.py --model-type diffusion --output-dir output/adult/med/diffusion --world-indexes "32"


python fit_causal_models_gen_eval_counterfactuals.py --model-type causalflow --output-dir output/adult/med/causalflow --world-indexes "0"
python fit_causal_models_gen_eval_counterfactuals.py --model-type causalflow --output-dir output/adult/med/causalflow --world-indexes "1"
python fit_causal_models_gen_eval_counterfactuals.py --model-type causalflow --output-dir output/adult/med/causalflow --world-indexes "2"
python fit_causal_models_gen_eval_counterfactuals.py --model-type causalflow --output-dir output/adult/med/causalflow --world-indexes "3"
python fit_causal_models_gen_eval_counterfactuals.py --model-type causalflow --output-dir output/adult/med/causalflow --world-indexes "4"
python fit_causal_models_gen_eval_counterfactuals.py --model-type causalflow --output-dir output/adult/med/causalflow --world-indexes "5"
python fit_causal_models_gen_eval_counterfactuals.py --model-type causalflow --output-dir output/adult/med/causalflow --world-indexes "6"
python fit_causal_models_gen_eval_counterfactuals.py --model-type causalflow --output-dir output/adult/med/causalflow --world-indexes "7"
python fit_causal_models_gen_eval_counterfactuals.py --model-type causalflow --output-dir output/adult/med/causalflow --world-indexes "8"
python fit_causal_models_gen_eval_counterfactuals.py --model-type causalflow --output-dir output/adult/med/causalflow --world-indexes "9"
python fit_causal_models_gen_eval_counterfactuals.py --model-type causalflow --output-dir output/adult/med/causalflow --world-indexes "10"
python fit_causal_models_gen_eval_counterfactuals.py --model-type causalflow --output-dir output/adult/med/causalflow --world-indexes "11"
python fit_causal_models_gen_eval_counterfactuals.py --model-type causalflow --output-dir output/adult/med/causalflow --world-indexes "12"
python fit_causal_models_gen_eval_counterfactuals.py --model-type causalflow --output-dir output/adult/med/causalflow --world-indexes "13"
python fit_causal_models_gen_eval_counterfactuals.py --model-type causalflow --output-dir output/adult/med/causalflow --world-indexes "14"
python fit_causal_models_gen_eval_counterfactuals.py --model-type causalflow --output-dir output/adult/med/causalflow --world-indexes "15"
python fit_causal_models_gen_eval_counterfactuals.py --model-type causalflow --output-dir output/adult/med/causalflow --world-indexes "16"
python fit_causal_models_gen_eval_counterfactuals.py --model-type causalflow --output-dir output/adult/med/causalflow --world-indexes "17"
python fit_causal_models_gen_eval_counterfactuals.py --model-type causalflow --output-dir output/adult/med/causalflow --world-indexes "18"
python fit_causal_models_gen_eval_counterfactuals.py --model-type causalflow --output-dir output/adult/med/causalflow --world-indexes "19"
python fit_causal_models_gen_eval_counterfactuals.py --model-type causalflow --output-dir output/adult/med/causalflow --world-indexes "20"
python fit_causal_models_gen_eval_counterfactuals.py --model-type causalflow --output-dir output/adult/med/causalflow --world-indexes "21"
python fit_causal_models_gen_eval_counterfactuals.py --model-type causalflow --output-dir output/adult/med/causalflow --world-indexes "22"
python fit_causal_models_gen_eval_counterfactuals.py --model-type causalflow --output-dir output/adult/med/causalflow --world-indexes "23"
python fit_causal_models_gen_eval_counterfactuals.py --model-type causalflow --output-dir output/adult/med/causalflow --world-indexes "24"
python fit_causal_models_gen_eval_counterfactuals.py --model-type causalflow --output-dir output/adult/med/causalflow --world-indexes "25"
python fit_causal_models_gen_eval_counterfactuals.py --model-type causalflow --output-dir output/adult/med/causalflow --world-indexes "26"
python fit_causal_models_gen_eval_counterfactuals.py --model-type causalflow --output-dir output/adult/med/causalflow --world-indexes "27"
python fit_causal_models_gen_eval_counterfactuals.py --model-type causalflow --output-dir output/adult/med/causalflow --world-indexes "28"
python fit_causal_models_gen_eval_counterfactuals.py --model-type causalflow --output-dir output/adult/med/causalflow --world-indexes "29"
python fit_causal_models_gen_eval_counterfactuals.py --model-type causalflow --output-dir output/adult/med/causalflow --world-indexes "30"
python fit_causal_models_gen_eval_counterfactuals.py --model-type causalflow --output-dir output/adult/med/causalflow --world-indexes "31"
python fit_causal_models_gen_eval_counterfactuals.py --model-type causalflow --output-dir output/adult/med/causalflow --world-indexes "32"
